#!/bin/bash
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
  DIR=$(dirname $(readlink -f $0))
elif [[ "$unamestr" == "Darwin" ]]; then
  cmd=$(which "$0")
  if [ -L "$cmd" ]; then
    cmd=$(readlink "$cmd")
  fi
  DIR=$(dirname "$cmd")
else
  echo "Only Linux and Mac OS X are supported!"
  exit
fi

unset PYTHONPATH
# Please put your full path to your environment
source /root/qira-1.3/venv/bin/activate
exec /usr/bin/env python2.7 $DIR/middleware/qira.py $*
