#!/bin/bash
set -e

if [ -z $1 ]; then
  echo "usage: $0 <target binary>"
  exit -1
fi

rm -f /tmp/qira_binary
ln -s $(realpath $1) /tmp/qira_binary

# build qemu if we have the source
if [ -d "qemu/qemu-latest" ]; then
  pushd .
  cd qemu/qemu-latest
  make -j32
  popd
fi

# detect which qemu to run based on the file
shift
qira-i386 -singlestep /tmp/qira_binary $@

