FROM ubuntu:16.04


RUN apt-get update && apt-get -y install git make gcc python ninja-build
RUN apt-get -y install pkg-config zlib1g-dev libglib2.0-dev libpixman-1-dev



RUN git clone https://github.com/geohot/qemu.git --depth 1 --branch qira /qemu_build/

WORKDIR /qemu_build/



RUN ./configure --target-list=x86_64-linux-user \
     --enable-tcg-interpreter                   \
     --enable-debug-tcg                         \
     --cpu=unknown                              \
     --python=python  && make -j$(getconf _NPROCESSORS_ONLN)


COPY  q2.patch q2.patch
RUN git apply q2.patch
RUN make -j$(getconf _NPROCESSORS_ONLN)



