#!/usr/bin/env python2
import os
import sys
import json

import cachegen
import cacheserver

file_cache = {}

if __name__ == "__main__":
  filename = os.path.realpath(sys.argv[2])
  file_cache[filename] = cachegen.parse_file(filename)
  dat = (cachegen.object_cache, file_cache, cachegen.xref_cache)
  f = open(sys.argv[1], "wb")
  json.dump(dat, f)
  f.close()

  cacheserver.start(dat)





