/** @file
 *
 * "ru" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "ru" keyboard mapping */
struct key_mapping ru_mapping[] __keymap = {
};
