/** @file
 *
 * "gr" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "gr" keyboard mapping */
struct key_mapping gr_mapping[] __keymap = {
};
