/** @file
 *
 * "pt" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "pt" keyboard mapping */
struct key_mapping pt_mapping[] __keymap = {
	{ 0x1c, 0x1d },	/* 0x1c => 0x1d */
	{ 0x1d, 0x1b },	/* 0x1d => 0x1b */
	{ 0x22, 0x5e },	/* '"' => '^' */
	{ 0x27, 0x7e },	/* '\'' => '~' */
	{ 0x2f, 0x3b },	/* '/' => ';' */
	{ 0x3f, 0x3a },	/* '?' => ':' */
	{ 0x5b, 0x27 },	/* '[' => '\'' */
	{ 0x5c, 0x5d },	/* '\\' => ']' */
	{ 0x5d, 0x5b },	/* ']' => '[' */
	{ 0x60, 0x27 },	/* '`' => '\'' */
	{ 0x7b, 0x60 },	/* '{' => '`' */
	{ 0x7c, 0x7d },	/* '|' => '}' */
	{ 0x7d, 0x7b },	/* '}' => '{' */
	{ 0x7e, 0x22 },	/* '~' => '"' */
};
