/** @file
 *
 * "us" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "us" keyboard mapping */
struct key_mapping us_mapping[] __keymap = {
};
