/** @file
 *
 * "cf" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "cf" keyboard mapping */
struct key_mapping cf_mapping[] __keymap = {
	{ 0x23, 0x2f },	/* '#' => '/' */
	{ 0x3c, 0x27 },	/* '<' => '\'' */
	{ 0x3e, 0x2e },	/* '>' => '.' */
	{ 0x40, 0x22 },	/* '@' => '"' */
	{ 0x5c, 0x3c },	/* '\\' => '<' */
	{ 0x5e, 0x3f },	/* '^' => '?' */
	{ 0x60, 0x23 },	/* '`' => '#' */
	{ 0x7c, 0x3e },	/* '|' => '>' */
	{ 0x7e, 0x7c },	/* '~' => '|' */
};
