/** @file
 *
 * "mk" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "mk" keyboard mapping */
struct key_mapping mk_mapping[] __keymap = {
};
