/** @file
 *
 * "th" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "th" keyboard mapping */
struct key_mapping th_mapping[] __keymap = {
};
