/** @file
 *
 * "ro" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "ro" keyboard mapping */
struct key_mapping ro_mapping[] __keymap = {
};
