/** @file
 *
 * "lt" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "lt" keyboard mapping */
struct key_mapping lt_mapping[] __keymap = {
};
