/** @file
 *
 * "pl" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "pl" keyboard mapping */
struct key_mapping pl_mapping[] __keymap = {
};
