/** @file
 *
 * "cz" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "cz" keyboard mapping */
struct key_mapping cz_mapping[] __keymap = {
	{ 0x21, 0x2b },	/* '!' => '+' */
	{ 0x2d, 0x3d },	/* '-' => '=' */
	{ 0x2f, 0x2d },	/* '/' => '-' */
	{ 0x31, 0x2b },	/* '1' => '+' */
	{ 0x3c, 0x2c },	/* '<' => ',' */
	{ 0x3e, 0x2e },	/* '>' => '.' */
	{ 0x3f, 0x2d },	/* '?' => '-' */
	{ 0x5d, 0x29 },	/* ']' => ')' */
	{ 0x5f, 0x3d },	/* '_' => '=' */
	{ 0x60, 0x3b },	/* '`' => ';' */
	{ 0x7d, 0x29 },	/* '}' => ')' */
	{ 0x7e, 0x3b },	/* '~' => ';' */
};
