/** @file
 *
 * "az" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "az" keyboard mapping */
struct key_mapping az_mapping[] __keymap = {
	{ 0x23, 0x27 },	/* '#' => '\'' */
	{ 0x24, 0x3b },	/* '$' => ';' */
	{ 0x26, 0x3f },	/* '&' => '?' */
	{ 0x2f, 0x2e },	/* '/' => '.' */
	{ 0x3a, 0x49 },	/* ':' => 'I' */
	{ 0x3f, 0x2c },	/* '?' => ',' */
	{ 0x40, 0x22 },	/* '@' => '"' */
	{ 0x5e, 0x3a },	/* '^' => ':' */
	{ 0x7c, 0x2f },	/* '|' => '/' */
};
